---
# deploy.yml

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: terminateInstances

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: launch
      name: ansible_aws_demo_2

- hosts: ansible_aws_demo_2
  roles:
    - deploy
    - nginx

- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - debug:
      msg: "{{ ec2_instance }}"

    - name: Check HTTP status code
      uri:
        url: http://{{ ec2_instance.public_dns_name }}:80/
