---
# roles/createAMI/tasks/main.yml

- name: Create AMI
  ec2_ami:
    region: "{{ region }}"
    instance_id: "{{ ec2_instance_id }}"
    name: "{{ ami_name }}"
    wait: yes
    state: present
  register: ami
