- name: Configure Elastic Load Balancers
  ec2_elb_lb:
    region: "{{ region }}"
    name: "{{ elb_name }}"
    state: present
    zones: "{{ zone }}"
    connection_draining_timeout: 60
    listeners:
      - protocol: http
        load_balancer_port: 8000
        instance_port: 8000
    health_check:
      ping_protocol: http
      ping_port: 8000
      ping_path: "/"
      response_timeout: 10
      interval: 60
      unhealthy_threshold: 10
      healthy_threshold: 2
  register: elb_result
