---
# roles/nginx/tasks/main.yml

- name: Install Nginx
  apt:
    pkg: nginx
    state: present
  become: yes

- name: Configure Nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  become: yes

- name: Allow Nginx
  command: ufw allow 'Nginx HTTP'
  become: yes

- name: Enable and start Nginx
  service:
    name: nginx
    enabled: yes
    state: restarted
  become: yes
