- name: Get timestamp from the system
  shell: "date +%d%m%Y-%H%M%S"
  register: tstamp

- name: Create Launch Configuration
  ec2_lc:
    region: "{{ region }}"
    name: "webapp-{{ tstamp.stdout }}"
    image_id: "{{ ami_id }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    security_groups: "{{ security_groups }}"
    volumes: "{{ volumes }}"
    instance_monitoring: yes
