- name: Create Launch Configuration
  ec2_lc:
    region: "{{ region }}"
    name: "{{ lc_name }}"
    image_id: "{{ ami_id }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    security_groups: "{{ name }}"
    volumes: "{{ volumes }}"
    instance_monitoring: yes
