---
# roles/launch/tasks/main.yml

- name: Search for the latest Ubuntu 16.04 AMI
  ec2_ami_find:
    region: "{{ region }}"
    name: "ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"
    owner: 099720109477
    sort: name
    sort_order: descending
    sort_end: 1
    no_result_action: fail
  register: ami_result

- name: Create Security Group
  ec2_group:
    name: "{{ name }}"
    description: "Ansible Security Group"
    vpc_id: "{{ vpc_id }}"
    #profile: "{{ aws_profile }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
        - 80
        - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 80

- name: Launch new instance
  ec2:
    region: "{{ region }}"
    keypair: "{{ keypair }}"
    zone: "{{ zone }}"
    group: "{{ name }}"
    image: "{{ ami_result.results[0].ami_id }}"
    instance_type: "{{ instance_type }}"
    instance_tags:
      Name: "{{ name }}"
    volumes: "{{ volumes }}"
    wait: yes
  register: ec2

- name: Add new instances to host group
  add_host:
    name: "{{ item.public_dns_name }}"
    groups: "{{ name }}"
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for instance to boot
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 5
    timeout: 120
    state: started
  with_items: "{{ ec2.instances }}"

- name: Set fact of ec2.instances
  set_fact:
    ec2_instance: "{{ ec2.instances[0] }}"
